In [128]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [129]:
df=pd.read_csv("sample_submission.csv")
df

PassengerId  Transported
0        0013_01        False
1        0018_01        False
2        0019_01        False
3        0021_01        False
4        0023_01        False
...          ...          ...
4272     9266_02        False
4273     9269_01        False
4274     9271_01        False
4275     9273_01        False
4276     9277_01        False

[4277 rows x 2 columns]

In [116]:
df.describe()

PassengerId Transported
count         4277        4277
unique        4277           1
top        0013_01       False
freq             1        4277

In [117]:
df.isna().sum()

PassengerId    0
Transported    0
dtype: int64

# To find outliers

In [118]:
df['Transported'].unique()

array([False])

In [119]:
# def IQR_values(df,column_name):
#     q1=df[column_name].quantile(0.25)
#     q2=df[column_name].quantile(0.50)
#     q3=df[column_name].quantile(0.75)
#     IQR=q3-q1
#     lower_limit=q1-1.5*IQR
#     upper_limit=q3+1.5*IQR
#     return lower_limit,upper_limit
# outlier={}
# for column in df.columns:
#     lower_limit,upper_limit=IQR_values(df,column)
#     outlier[column]=[lower_limit,upper_limit]
#     outlier

This df has no outliers since columns of df is obj and bool

# Standard Scaling

In [130]:
from sklearn.preprocessing import StandardScaler
StdS=StandardScaler()

In [131]:
df1=df.drop('Transported',axis=1)
df1

PassengerId
0        0013_01
1        0018_01
2        0019_01
3        0021_01
4        0023_01
...          ...
4272     9266_02
4273     9269_01
4274     9271_01
4275     9273_01
4276     9277_01

[4277 rows x 1 columns]

In [132]:
x=StdS.fit_transform(df1)
x

array([[-1.70342646],
       [-1.70158544],
       [-1.70121723],
       ...,
       [ 1.70541369],
       [ 1.7061501 ],
       [ 1.70762292]])

In [133]:
df2=pd.DataFrame(x,columns=df1.columns)
df.update(df2)
df

PassengerId  Transported
0      -1.703426        False
1      -1.701585        False
2      -1.701217        False
3      -1.700481        False
4      -1.699744        False
...          ...          ...
4272    1.703576        False
4273    1.704677        False
4274    1.705414        False
4275     1.70615        False
4276    1.707623        False

[4277 rows x 2 columns]

# LabelEncoding

In [134]:
from sklearn.preprocessing import LabelEncoder
lenc=LabelEncoder()

In [136]:
t=['Transported']
df[t]=df[t].apply(lenc.fit_transform)
df.update(df[t])
df

PassengerId  Transported
0      -1.703426            0
1      -1.701585            0
2      -1.701217            0
3      -1.700481            0
4      -1.699744            0
...          ...          ...
4272    1.703576            0
4273    1.704677            0
4274    1.705414            0
4275     1.70615            0
4276    1.707623            0

[4277 rows x 2 columns]

# Linear Modelling

In [152]:
x=df['PassengerId'].values
y=df['Transported'].values
x

array([-1.703426460470618, -1.7015854364080485, -1.7012172315955347, ...,
       1.7054136937829618, 1.7061501034079896, 1.707622922658045],
      dtype=object)

In [154]:
x=x.reshape(-1,1)
x

array([[-1.703426460470618],
       [-1.7015854364080485],
       [-1.7012172315955347],
       ...,
       [1.7054136937829618],
       [1.7061501034079896],
       [1.707622922658045]], dtype=object)

In [155]:
from sklearn.model_selection import train_test_split

In [156]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
x_test.shape

(856, 1)

In [157]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [158]:
lr.fit(x_train,y_train)

LinearRegression()

In [159]:
lr_pred=lr.predict(x_test)
lr_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [160]:
from sklearn.metrics import mean_squared_error

In [161]:
mean_squared_error(y_test,lr_pred)

0.0

# SVM

In [164]:
from sklearn.svm import SVR
svr=SVR(kernel='linear')
svr.fit(x_train,y_train,sample_weight=None)
svr_pred=svr.predict(x_test)

In [166]:
from sklearn.metrics import r2_score
r2_score(y_test,svr_pred)

1.0

# DecisionTree

In [168]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(criterion="absolute_error")
dtr.fit(x_train,y_train)
dtr_pred=dtr.predict(x_test)
mean_squared_error(y_test,dtr_pred)

0.0

# Random Forest

In [170]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(criterion="squared_error")
rfr.fit(x_train,y_train)
rfr_pred=rfr.predict(x_test)
r2_score(y_test,rfr_pred)

1.0