In [1]:
#pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
a=[2,3,4,5,6] 

In [5]:
a

[2, 3, 4, 5, 6]

In [7]:
b=np.array(a) #creating a 1-D array
b

array([2, 3, 4, 5, 6])

In [8]:
b.ndim #ndim property

1

In [59]:
c=np.array([[1,0,0],[0,1,0],[0,0,1]]) #creating a 2_D array
c

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [60]:
c.ndim

2

In [61]:
c.itemsize #itemsize property(byte size of each element)

4

In [12]:
c.dtype #dtype property

dtype('int32')

In [27]:
c.shape #shape property

(3, 3)

In [28]:
c[1:3,0:2][1]

array([0, 0])

In [64]:
c=np.array([[1,0,0],[0,1,0],[0,0,1]],dtype=np.float64) #change datatype of element
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
c.itemsize

8

In [15]:
c.size #size property

9

In [17]:
#c=np.array([[1,0,0],[0,1,0],[0,0,1]],dtype=np.complex)
#c

In [27]:
np.zeros((2,3)) #zeros() function

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
c[2][2]

1

In [18]:
np.ones((2,3)) #ones()function

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
l=range(5) #range function
l

range(0, 5)

In [21]:
l[0]

0

In [22]:
l[3]

3

In [70]:
e=np.random.randint(12,size=(2,3)) #random.randint() function
e

array([[9, 1, 8],
       [5, 4, 9]])

In [71]:
e.min() #min() function

1

In [72]:
e.max() #max() function

9

In [73]:
e.sum() #sum() function

36

In [74]:
e.sum(axis=0) #sum across coloumn

array([14,  5, 17])

In [75]:
e.sum(axis=1) #sum across rows

array([18, 18])

In [76]:
np.transpose(e) #transpose() function

array([[9, 5],
       [1, 4],
       [8, 9]])

In [77]:
np.sqrt(e) #sqrt() function

array([[3.        , 1.        , 2.82842712],
       [2.23606798, 2.        , 3.        ]])

In [78]:
np.std(e) #std() function

2.943920288775949

In [79]:
np.arange(1,10,2) #arange() function

array([1, 3, 5, 7, 9])

In [80]:
np.linspace(0,1,5) #linspace() function

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
d=np.arange(8)
d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
d.reshape(8,-1) #reshape() function

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [32]:
d.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [69]:
d.ravel() #ravel() function

array([0, 1, 2, 3, 4, 5, 6, 7])

In [36]:
f=[1,2,3,4,5,6]
np.asarray(f)

array([1, 2, 3, 4, 5, 6])

In [37]:
np.asmatrix([f[0:3],f[3:6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [38]:
np.resize(f,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

# Operations in array

In [82]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [47]:
print(a)


[[1 2 3]
 [4 5 6]]


In [48]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
np.append(a,b,axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [50]:
np.insert(a,1,0,axis=0)

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6]])

In [51]:
b.flatten()

array([ 7,  8,  9, 10, 11, 12])

In [52]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [53]:
a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [54]:
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [55]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

# matrix products

In [57]:
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

# PANDAS

In [48]:

b=pd.DataFrame(a, columns=['age'])
b

age
0   12
1   23
2   45
3   65

In [49]:
b['age'][1:3]

1    23
2    45
Name: age, dtype: int64

In [50]:
b.age[0]

12

In [53]:
c=b.groupby('age').mean()
c

Empty DataFrame
Columns: []
Index: [12, 23, 45, 65]

In [54]:
d={'age':[1,2,3,4,5,6],'year':[123,12,145,167,189,190]}
f=pd.DataFrame(d)
f

age  year
0    1   123
1    2    12
2    3   145
3    4   167
4    5   189
5    6   190

In [39]:
f['sum1']=f['age']+f['year']
f

age  year  sum1
0    1   123   124
1    2    12    14
2    3   145   148
3    4   167   171
4    5   189   194
5    6   190   196

In [20]:
pd.Series(b['year'])

0    2000
1    2022
2    2014
3    2019
Name: year, dtype: int64

In [130]:
#pip install os

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os


In [31]:
import os

In [32]:
os.getcwd()

'C:\\Users\\JOS\\Documents'

In [33]:
os.chdir('c:\\Users\\JOS\\Downloads')

In [34]:
df=pd.read_csv("sample_submission.csv")

In [35]:
df

PassengerId  Transported
0        0013_01        False
1        0018_01        False
2        0019_01        False
3        0021_01        False
4        0023_01        False
...          ...          ...
4272     9266_02        False
4273     9269_01        False
4274     9271_01        False
4275     9273_01        False
4276     9277_01        False

[4277 rows x 2 columns]

In [ ]:
df['departed]=

In [142]:
df.head(10)

PassengerId  Transported
0     0013_01        False
1     0018_01        False
2     0019_01        False
3     0021_01        False
4     0023_01        False
5     0027_01        False
6     0029_01        False
7     0032_01        False
8     0032_02        False
9     0033_01        False

In [141]:
df.tail()

PassengerId  Transported
4272     9266_02        False
4273     9269_01        False
4274     9271_01        False
4275     9273_01        False
4276     9277_01        False

In [7]:
df.describe()

PassengerId Transported
count         4277        4277
unique        4277           1
top        0013_01       False
freq             1        4277

In [7]:
d=np.matrix([[1,2],[3,]])
d

matrix([[list([1, 2]), list([3])]], dtype=object)

In [10]:
d_asarray=np.asarray(d)
d_asarray

array([[list([1, 2]), list([3])]], dtype=object)

In [16]:
e=np.random.randint(0,50)
e

14