In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("sample_submission.csv")
df

PassengerId  Transported
0        0013_01        False
1        0018_01        False
2        0019_01        False
3        0021_01        False
4        0023_01        False
...          ...          ...
4272     9266_02        False
4273     9269_01        False
4274     9271_01        False
4275     9273_01        False
4276     9277_01        False

[4277 rows x 2 columns]

In [3]:
df.describe()

PassengerId Transported
count         4277        4277
unique        4277           1
top        0013_01       False
freq             1        4277

In [4]:
df.isna().sum()

PassengerId    0
Transported    0
dtype: int64

# To find outliers

In [5]:
df['Transported'].unique()

array([False])

In [6]:
# def IQR_values(df,column_name):
#     q1=df[column_name].quantile(0.25)
#     q2=df[column_name].quantile(0.50)
#     q3=df[column_name].quantile(0.75)
#     IQR=q3-q1
#     lower_limit=q1-1.5*IQR
#     upper_limit=q3+1.5*IQR
#     return lower_limit,upper_limit
# outlier={}
# for column in df.columns:
#     lower_limit,upper_limit=IQR_values(df,column)
#     outlier[column]=[lower_limit,upper_limit]
#     outlier

This df has no outliers since columns of df is obj and bool

# Standard Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
StdS=StandardScaler()

In [8]:
df1=df.drop('Transported',axis=1)
df1

PassengerId
0        0013_01
1        0018_01
2        0019_01
3        0021_01
4        0023_01
...          ...
4272     9266_02
4273     9269_01
4274     9271_01
4275     9273_01
4276     9277_01

[4277 rows x 1 columns]

In [9]:
x=StdS.fit_transform(df1)
x

array([[-1.70342646],
       [-1.70158544],
       [-1.70121723],
       ...,
       [ 1.70541369],
       [ 1.7061501 ],
       [ 1.70762292]])

In [10]:
df2=pd.DataFrame(x,columns=df1.columns)
df.update(df2)
df

PassengerId  Transported
0      -1.703426        False
1      -1.701585        False
2      -1.701217        False
3      -1.700481        False
4      -1.699744        False
...          ...          ...
4272    1.703576        False
4273    1.704677        False
4274    1.705414        False
4275     1.70615        False
4276    1.707623        False

[4277 rows x 2 columns]

# LabelEncoding

In [11]:
from sklearn.preprocessing import LabelEncoder
lenc=LabelEncoder()

In [12]:
t=['Transported']
df[t]=df[t].apply(lenc.fit_transform)
df.update(df[t])
df

PassengerId  Transported
0      -1.703426            0
1      -1.701585            0
2      -1.701217            0
3      -1.700481            0
4      -1.699744            0
...          ...          ...
4272    1.703576            0
4273    1.704677            0
4274    1.705414            0
4275     1.70615            0
4276    1.707623            0

[4277 rows x 2 columns]

# Linear Modelling

In [13]:
x=df['PassengerId'].values
y=df['Transported'].values
x

array([-1.703426460470618, -1.7015854364080485, -1.7012172315955347, ...,
       1.7054136937829618, 1.7061501034079896, 1.707622922658045],
      dtype=object)

In [14]:
x=x.reshape(-1,1)
x

array([[-1.703426460470618],
       [-1.7015854364080485],
       [-1.7012172315955347],
       ...,
       [1.7054136937829618],
       [1.7061501034079896],
       [1.707622922658045]], dtype=object)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)
x_test.shape

(856, 1)

In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [18]:
lr.fit(x_train,y_train)

LinearRegression()

In [19]:
lr_pred=lr.predict(x_test)
lr_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [20]:
from sklearn.metrics import mean_squared_error

In [21]:
mean_squared_error(y_test,lr_pred)

0.0

# SVM

In [22]:
from sklearn.svm import SVR
svr=SVR(kernel='linear')
svr.fit(x_train,y_train,sample_weight=None)
svr_pred=svr.predict(x_test)

In [23]:
from sklearn.metrics import r2_score
r2_score(y_test,svr_pred)

1.0

# DecisionTree

In [24]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(criterion="absolute_error")
dtr.fit(x_train,y_train)
dtr_pred=dtr.predict(x_test)
mean_squared_error(y_test,dtr_pred)

0.0

# Random Forest

In [25]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(criterion="squared_error")
rfr.fit(x_train,y_train)
rfr_pred=rfr.predict(x_test)
r2_score(y_test,rfr_pred)

1.0

# Naive Bayes

In [26]:
from sklearn.naive_bayes import GaussianNB

In [27]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
gnb_pred=gnb.predict(x_test)
mean_squared_error(y_test,gnb_pred)

0.0

# KNeighbor regressor

In [28]:
from sklearn.neighbors import KNeighborsRegressor

In [29]:
knr=KNeighborsRegressor(n_neighbors=5,metric='euclidean')
knr.fit(x_train,y_train)
knr_pred=knr.predict(x_test)
from sklearn.metrics import max_error
max_error(y_test,knr_pred)

0.0

# Cross_validation

In [30]:
from sklearn.model_selection import cross_val_score

In [31]:
models={'linear':LinearRegression(), 'SVR':SVR(), 'Decision_tree':DecisionTreeRegressor(), 'Random_forest':RandomForestRegressor(), 'GaussianNB':GaussianNB(), 'knn':KNeighborsRegressor()}

In [32]:
res=[]
for i in models:
    model=models[i]
    scores=cross_val_score(model,x,y,cv=5)
    a=(i,scores.mean())
    res.append(a)
res

[('linear', 1.0),
 ('SVR', 1.0),
 ('Decision_tree', 1.0),
 ('Random_forest', 1.0),
 ('GaussianNB', 1.0),
 ('knn', 1.0)]

# Tuning Parameters

In [33]:
from sklearn.model_selection import KFold

In [34]:
linr_params={'fit_intercept':[True,False]}
decstree_params={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'splitter':['best','random']}
radmforst_params={'criterion':['squared_error','friedman_mse','absolute_error','poisson'],'n_estimators':[100,150,175]}
#SVC_params={'kernel':['linear','poly','rbf','sigmoid','precomputed'],'gamma':['scale','auto']}
gauss_params={'var_smoothing':[1e-9,1e-8,1e-10]}
knn_params={'n_neighbors':[3,5,8,9],'weights':['uniform','distance']}

In [35]:
model_details={'lr':{'model':LinearRegression(),'params':linr_params},
                'gaussian':{'model':GaussianNB(),'params':gauss_params},
                'dtc':{'model':DecisionTreeRegressor(),'params':decstree_params},
                'rfc':{'model':RandomForestRegressor(),'params':radmforst_params},
                'knn':{'model':KNeighborsRegressor(),'params':knn_params},
                #'svc':{'model':SVC(),'params':SVC_params}
              }

In [37]:
result=[]
for model_name in model_details:
    model_dict=model_details.get(model_name)
    print(model_dict)#get models & their parameters as dict
    model=model_dict.get('model')
    print(model)
    params=model_dict.get('params')
    print(params)
    kf=KFold(n_splits=5)
    kf.get_n_splits(model)
    print(kf)
    KFold(n_splits=2, random_state=None, shuffle=False)
    for i, (train_index, test_index) in enumerate(kf.split(x)):
        print(f"Fold {i}:")
        print(f"  Train: index={train_index}")
        print(f"  Test:  index={test_index}")
#print(result)

{'model': LinearRegression(), 'params': {'fit_intercept': [True, False]}}
LinearRegression()
{'fit_intercept': [True, False]}
KFold(n_splits=5, random_state=None, shuffle=False)
Fold 0:
  Train: index=[ 856  857  858 ... 4274 4275 4276]
  Test:  index=[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 1